[tools]
"tuist" = "4.38.2"
"swiftlint" = "0.54.0"
"swiftformat" = "0.52.10"
"swift" = "5.9.2"
"node" = "22.12.0"
"pnpm" = "9.15.1"
"git-cliff" = "2.4.0"

[plugins]
tuist = "https://github.com/asdf-community/asdf-tuist"
swift = "https://github.com/fcrespo82/asdf-swift"
virtualos = "https://github.com/tuist/asdf-virtualos"
