[tools]
"tuist" = "4.38.2"
"swiftlint" = "0.54.0"
"swiftformat" = "0.52.10"
"swift" = "5.9.2"
"node" = "22.13.1"
"pnpm" = "9.15.2"
"git-cliff" = "2.4.0"

[alias]
tuist = "asdf:asdf-community/asdf-tuist"
swift = "asdf:fcrespo82/asdf-swift"
virtualos = "asdf:tuist/asdf-virtualos"
