#!/usr/bin/env bash
# mise description="Installs the project dependencies"

set -euo pipefail

if [[ "$(uname)" == "Darwin" ]]; then
    tuist install --path $MISE_PROJECT_ROOT
fi
pnpm install -C $MISE_PROJECT_ROOT/docs
