#!/bin/bash
# mise description = "Lints the project fixing the fixable issues"
set -euo pipefail

swiftformat $MISE_PROJECT_ROOT
swiftlint lint --fix --quiet --config $MISE_PROJECT_ROOT/.swiftlint.yml $MISE_PROJECT_ROOT/Sources
