name: Docs

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Install
        run: |
          mise run install
      - name: Build
        run: |
          mise run docs:build
