name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release-${{ github.head_ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: "1"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Continuous
    runs-on: "macos-13"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: true
      - uses: jdx/mise-action@v2
        if: "!startsWith(github.event.head_commit.message, 'release')"
      - run: mise run install
        if: "!startsWith(github.event.head_commit.message, 'release')"
      - name: bundle
        if: "!startsWith(github.event.head_commit.message, 'release')"
        env:
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
          CERTIFICATE_ENCRYPTION_PASSWORD: ${{ secrets.CERTIFICATE_ENCRYPTION_PASSWORD }}
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_CONFIG_TOKEN }}
        run: mise run bundle
      - name: Get next version
        if: "!startsWith(github.event.head_commit.message, 'release')"
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "VERSION=$(git-cliff --bumped-version)" >> $GITHUB_ENV
      - name: Generate changelog
        if: "!startsWith(github.event.head_commit.message, 'release')"
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git-cliff --bump -o CHANGELOG.md
      # - name: Generate release notes
      #   if: "!startsWith(github.event.head_commit.message, 'release')"
      #   id: release-notes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     echo "RELEASE_NOTES=$(git-cliff --unreleased)" >> $GITHUB_ENV
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: "!startsWith(github.event.head_commit.message, 'release')"
        with:
          commit_message: release ${{ env.VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: "!startsWith(github.event.head_commit.message, 'release')"
        with:
          draft: false
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          make_latest: true
          generate_release_notes: true
          files: |
            build/artifacts/virtualos.zip
            build/artifacts/SHASUMS256.txt
            build/artifacts/SHASUMS512.txt
